SET SCHEMA DMVSEC;

------------------------ CREATE TABLE CDL_MEDCERT_ERRCODES ----------------------------------
CREATE TABLE DMVSEC.CDL_MEDCERT_ERRCODES
(
	ID					NUMBER              NOT NULL,	
	ERROR_CODE  		NUMBER				NOT NULL,	
	ERROR_TEXT	  		VARCHAR2(100 BYTE)  NOT NULL        
);

--------------PRIMARY KEY------------------
ALTER TABLE DMVSEC.CDL_MEDCERT_ERRCODES
  ADD (
    CONSTRAINT ERRCODES_PK PRIMARY KEY (ID)
  );    

 
---- CREATE SYNONYMS ----------------------------------------------------------------------------
CREATE OR REPLACE SYNONYM EUSR_DMVSEC.CDL_MEDCERT_ERRCODES FOR DMVSEC.CDL_MEDCERT_ERRCODES;

--- PERMISSIONS ---------------------------------------------------------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON DMVSEC.CDL_MEDCERT_ERRCODES TO EUSR_DMVSEC;
  
-----------------CREATE SEQUENCE----------------------
CREATE SEQUENCE DMVSEC.SEQ_ERRCODES_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;

CREATE OR REPLACE SYNONYM EUSR_DMVSEC.SEQ_ERRCODES_ID FOR DMVSEC.SEQ_ERRCODES_ID;

GRANT INSERT, SELECT, UPDATE, DELETE ON DMVSEC.SEQ_ERRCODES_ID TO EUSR_DMVSEC;

-------------POPULATE ID BY SEQUENCE----------------- 

  CREATE OR REPLACE TRIGGER CDL_ERRCODES_TRIGGER
  BEFORE INSERT ON DMVSEC.CDL_MEDCERT_ERRCODES
  FOR EACH ROW
BEGIN
  SELECT DMVSEC.SEQ_ERRCODES_ID.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;
